version: "3"
services:
  web:
    build: ./frontend
    ports:
      - 5020:80
  
  db:
    build: ./db
    network_mode: host
    volumes:
      - ./db/pb_data:/app/pb_data
      - ./db/pb_migrations:/app/pb_migrations
  
  backend:
    network_mode: host
    build: ./backend

